// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAomFs_qxI4iAoHb2C59Pih7RDLzDsDhMo',
    appId: '1:72819227069:android:35d5489ccbcb19260ebad4',
    messagingSenderId: '72819227069',
    projectId: 'numo-customer-app',
    storageBucket: 'numo-customer-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBp4JtFOrQLtNle40efH9CCOPfZS5EQyug',
    appId: '1:72819227069:ios:69d45f1bd68d31ac0ebad4',
    messagingSenderId: '72819227069',
    projectId: 'numo-customer-app',
    storageBucket: 'numo-customer-app.appspot.com',
    androidClientId: '72819227069-6p639bckhqbv5fl47e2t7fjn1nnpi3jq.apps.googleusercontent.com',
    iosClientId: '72819227069-5n1nr7eo5fo3imm2sj1kbhvtjquskpqa.apps.googleusercontent.com',
    iosBundleId: 'com.nama.numocustomer',
  );
}
